spring:
  application:
    name: OnlineFilePreview
  mvc:
    favicon:
      enabled: false
    static-path-pattern: /**
  resources:
    static-locations: /,classpath:/resources/,classpath:/static/
server:
  port: 8088


libre-office:
  # Libre Office 的 bin 目录
  soffice-bin-file-path: "\"C:/Program Files/LibreOffice/program/soffice.bin\""
  convert-command:
    # Windows 和 Linux 都兼容
    office-to-pdf: ${libre-office.soffice-bin-file-path} --headless --invisible --convert-to %s %s --outdir %s